---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Create an incident
    snow_record:
     username: admin
     password: NgluVWo57OIr
     instance: dev73825
     state: present
     data:
      short_description: "This is a test incident opened by Ansible"
      severity: 3
      priority: 2
    register: new_incident
